name: "output_block_pipeline"

trigger:
 branches:
   include:
     - mian

pool:
  name:  Bank_app

stages:
  - stage: init_stage
    displayName: init
    jobs:
      - job: terraforminit
        steps:
           - template: template/init.yaml

        
  - stage: plan_stage
    displayName: plan
    jobs:
      - job: terraform_plan
        steps:
          - template: template/init.yaml

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/parent/dev'
              environmentServiceNameAzureRM: 'kaka'




            
          
